In [1]:
import numpy as np
import random

In [2]:
track=[
    [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
    [0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
    [0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
    [0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
    [0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
    [0,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0],
    [0,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0],
    [0,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0],
    [0,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0],
    [0,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0],
    [0,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0],]

In [3]:
copy=track[-1]
for i in range(25):
    track.append(copy)

In [4]:
track=np.array(track)

In [5]:
#declare actions
#declare starting points
#declare ending points
#declare policies
#declare values
#declare returns


In [6]:
height,width = track.shape
starting_points=[]
for i in range(width - 1):
    if track[height-1,i]==1:
        starting_points.append([height-1,i])
starting_points = np.array(starting_points)

In [7]:
ending_points=[]
for i in range(4):
    ending_points.append([i+1,width - 1])
ending_points = np.array(ending_points)

In [8]:
policy=np.zeros(track.shape)

In [9]:
#initialize initial velocities in starting state so it moves
def drive():
    #choose starting state
    starting=starting_points[random.randint(0,len(starting_points))]



In [17]:
# state = ([x,y],[vx,vy]), 0.1125
actions = np.array([[0,0],[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1]])
steps = []
state = np.array([[35,5],[0,0]])
def restart(state):
    state[1] = np.zeros(2)
    state[0] = random.choice(starting_points)
while True:
    index = np.random.choice(np.arange(0,9), p=[0.1, 0.1125, 0.1125,.1125,.1125,.1125,.1125,.1125,.1125])
    state[1] = state[1] + actions[index]
    if state[1,0] > 0:
        state[1,0] = 0
    if state[1,0] < -5:
        state[1,0] = -5
    if state[1,1] < 0:
        state[1,1] = 0
    if state[1,1] > 5:
        state[1,1] = 5
    state[0] = state[0] + state[1]
    if any((state[0] == x).all() for x in ending_points):
        break
    elif np.logical_or(*(list(state[0] < np.array([0,0])))) or np.logical_or(*(list(state[0] > np.array([height - 1,width - 1])))) or track[tuple(state[0])] == 0:
        restart(state)
    #print(state[0])
    steps.append(list(state[0]))
print(steps)

[[35, 6], [35, 8], [35, 9], [35, 10], [35, 10], [35, 10], [35, 4], [34, 5], [32, 7], [30, 9], [27, 10], [35, 2], [34, 3], [33, 3], [31, 4], [30, 4], [29, 4], [28, 4], [28, 5], [27, 5], [26, 5], [24, 6], [21, 7], [18, 8], [16, 9], [13, 9], [10, 9], [6, 9], [1, 9], [35, 8], [35, 9], [35, 10], [35, 8], [35, 8], [35, 8], [35, 9], [34, 9], [33, 9], [31, 9], [30, 9], [28, 9], [25, 9], [23, 9], [20, 9], [18, 9], [17, 9], [15, 9], [13, 9], [12, 9], [10, 9], [9, 9], [8, 9], [8, 9], [7, 10], [35, 9], [35, 9], [34, 9], [34, 9], [33, 10], [35, 3], [34, 4], [32, 6], [30, 8], [27, 9], [24, 10], [35, 6], [35, 6], [35, 6], [35, 7], [35, 9], [35, 10], [35, 10], [35, 10], [35, 3], [35, 4], [34, 6], [32, 8], [30, 9], [28, 10], [26, 10], [24, 10], [21, 10], [35, 1], [35, 1], [35, 2], [34, 3], [32, 4], [30, 4], [27, 5], [24, 5], [21, 5], [17, 5], [13, 5], [8, 5], [3, 5], [35, 6], [34, 7], [32, 8], [30, 8], [27, 8], [25, 8], [23, 8], [21, 8], [19, 8], [18, 8], [17, 8], [15, 9], [12, 9], [9, 9], [5, 10], [35

In [15]:
steps

[array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4, 17]),
 array([ 4